### ISSUE TITLE
markdown-it plugins

### ISSUE THREAD

**Issue by MayanMisfit** [bradleytaunt/eleventy-taunt#2]
HI, how do you install plugins? is it directly into the nodjs folder or do they need to go into the markdown-it folder?

**Comment by bradleytaunt** [comment]
This theme just uses the default 11ty structure of adding / implementing plugins (`npm`). The best place to check out more on using plugins within 11ty can be found here:

https://www.11ty.io/docs/plugins/#adding-a-plugin

Hope this helps!
